DROP TABLE "ADMIN";
DROP TABLE "CART";
DROP TABLE "INQUIRY";
DROP TABLE "QUESTION";
DROP TABLE "NOTICE";
DROP TABLE "PMANAGE";
DROP TABLE "UMANAGE";
DROP TABLE "PRODUCT";
DROP TABLE "ORDER";
DROP TABLE "REVIEW";
DROP TABLE "FILE";
DROP TABLE "INQUIRYCOMMENT";
DROP TABLE "USER";

CREATE TABLE "ADMIN" (
   "ADMINID" VARCHAR2(30) NOT NULL,
   "ADMIN_PWD" VARCHAR2(100) NOT NULL
);

CREATE TABLE "CART" (
   "CARTCODE" NUMBER NOT NULL,
   "USERID" VARCHAR2(30) NOT NULL,
   "FCODE" NUMBER NOT NULL,
   "PCODE" NUMBER NOT NULL,
   "C_QUANTITY" NUMBER NOT NULL
);



CREATE TABLE "INQUIRY" (
   "CCODE" NUMBER NOT NULL,
   "USERID" VARCHAR2(30) NOT NULL,
   "ADMINID" VARCHAR2(30) NOT NULL,
   "CTITLE" VARCHAR2(30) NOT NULL,
   "CCONTENT" VARCHAR2(300) NOT NULL
);



CREATE TABLE "QUESTION" (
   "QCODE"   NUMBER    NOT NULL,
   "ADMINID"   VARCHAR2(30)    NOT NULL,
   "QNAME"   VARCHAR2(30)    NOT NULL,
   "QCONTENT"  VARCHAR2(300)   NOT NULL
);



CREATE TABLE "NOTICE" (
   "NCODE"   NUMBER      NOT NULL,
   "ADMINID"   VARCHAR2(30)      NOT NULL,
   "NTITLE"   VARCHAR2(300)      NOT NULL,
   "NDATE"  DATE  DEFAULT SYSDATE,
   "NCONTENT"   VARCHAR2(300)      NOT NULL
);



CREATE TABLE "PMANAGE" (
   "PMCODE"   NUMBER      NOT NULL,
   "ADMINID"   VARCHAR2(30)     NOT NULL,
   "PCODE"   NUMBER      NOT NULL,
   "PMDATE"   DATE     DEFAULT SYSDATE,
   "PMCONTENT"   VARCHAR2(300)   NOT NULL
);



CREATE TABLE "UMANAGE" (
   "UMCODE"  NUMBER   NOT NULL,
   "USERID"   VARCHAR2(30)      NOT NULL,
   "ADMINID"   VARCHAR2(30)     NOT NULL,
   "UMCONTENT"   VARCHAR2(300)    NOT NULL
);



CREATE TABLE "PRODUCT" (
   "PCODE"   NUMBER  NOT NULL,
   "PNAME"  VARCHAR2(30)    NOT NULL,
   "PRICE"   NUMBER   NOT NULL,
   "PTYPE"   VARCHAR2(30)    NOT NULL,
   "PCOLOR"   VARCHAR2(30)  NOT NULL
);

CREATE TABLE "ORDER" (
   "ORDERCODE"   NUMBER     NOT NULL,
   "PCODE"   NUMBER     NOT NULL,
   "ORDERDATE" DATE  DEFAULT SYSDATE,
   "QUANTITY"   NUMBER   NOT NULL,
   "USERID"   VARCHAR2(30)    NOT NULL
);



CREATE TABLE "REVIEW" (
   "RCODE"   NUMBER  NOT NULL,
   "RCONTENT"   VARCHAR2(300)      NULL,
   "RDATE"  DATE DEFAULT SYSDATE  ,
   "STAR"   NUMBER      NULL,
   "USERID"   VARCHAR2(30)      NOT NULL,
   "PCODE"   NUMBER    NOT NULL,
   "FCODE"   NUMBER NOT NULL
);



CREATE TABLE "FILE" (
   "FCODE"   NUMBER      NOT NULL,
   "PCODE"   NUMBER      NOT NULL,
   "FILEPATH"   VARCHAR2(300)  NOT NULL
);



CREATE TABLE "INQUIRYCOMMENT" (
   "ACODE"   NUMBER NOT NULL,
   "ADMINID"   VARCHAR2(30)    NOT NULL,
   "CCODE"   NUMBER   NOT NULL,
   "ACONTENT" VARCHAR2(300)      NULL,
   "NDATE"   DATE DEFAULT SYSDATE 
);



CREATE TABLE "USER" (
   "USERID"   VARCHAR2(30)     NOT NULL,
   "PASSWORD"  VARCHAR2(100)     NOT NULL,
   "USERNAME"  VARCHAR2(30)     NOT NULL,
   "ADDRESS"  VARCHAR2(300)     NOT NULL,
   "EMAIL"   VARCHAR2(100)    NOT NULL,
   "BIRTH"   NUMBER     NULL,
   "PHONE"   VARCHAR2(30)     NOT NULL
);

ALTER TABLE "USER" MODIFY BIRTH NUMBER;
ALTER TABLE "USER" RENAME TO "MEMBER";


ALTER TABLE "ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY (
   "ADMINID"
);

ALTER TABLE "CART" ADD CONSTRAINT "PK_CART" PRIMARY KEY (
   "CARTCODE",
   "USERID",
   "FCODE",
   "PCODE"
);

ALTER TABLE "INQUIRY" ADD CONSTRAINT "PK_INQUIRY" PRIMARY KEY (
   "CCODE",
   "USERID",
   "ADMINID"
);

ALTER TABLE "QUESTION" ADD CONSTRAINT "PK_QUESTION" PRIMARY KEY (
   "QCODE",
   "ADMINID"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
   "NCODE",
   "ADMINID"
);

ALTER TABLE "PMANAGE" ADD CONSTRAINT "PK_PMANAGE" PRIMARY KEY (
   "PMCODE",
   "ADMINID",
   "PCODE"
);

ALTER TABLE "UMANAGE" ADD CONSTRAINT "PK_UMANAGE" PRIMARY KEY (
   "UMCODE",
   "USERID",
   "ADMINID"
);

ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY (
   "PCODE"
);

ALTER TABLE "ORDER" ADD CONSTRAINT "PK_ORDER" PRIMARY KEY (
   "ORDERCODE",
   "PCODE"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
   "RCODE"
);

ALTER TABLE "FILE" ADD CONSTRAINT "PK_FILE" PRIMARY KEY ("FCODE","PCODE");

ALTER TABLE "INQUIRYCOMMENT" ADD CONSTRAINT "PK_INQUIRYCOMMENT" PRIMARY KEY ("ACODE","ADMINID");

ALTER TABLE "USER" ADD CONSTRAINT "PK_USER" PRIMARY KEY ("USERID");

ALTER TABLE "CART" ADD CONSTRAINT "FK_USER_TO_CART_1" FOREIGN KEY ("USERID")REFERENCES "MEMBER"("USERID") ON DELETE CASCADE;

ALTER TABLE "CART" ADD CONSTRAINT "FK_FILE_TO_CART_1" FOREIGN KEY ("FCODE","PCODE")REFERENCES "FILE" ("FCODE","PCODE") ON DELETE CASCADE;

ALTER TABLE "CART" ADD CONSTRAINT "FK_PRODUCT_TO_CART_1" FOREIGN KEY ("PCODE")REFERENCES "PRODUCT" ("PCODE") ON DELETE CASCADE;

ALTER TABLE "INQUIRY" ADD CONSTRAINT "FK_USER_TO_INQUIRY_1" FOREIGN KEY ("USERID")REFERENCES "MEMBER" ("USERID") ON DELETE CASCADE;

ALTER TABLE "INQUIRY" ADD CONSTRAINT "FK_ADMIN_TO_INQUIRY_1" FOREIGN KEY ("ADMINID")REFERENCES "ADMIN" ("ADMINID") ON DELETE CASCADE;

ALTER TABLE "QUESTION" ADD CONSTRAINT "FK_ADMIN_TO_QUESTION_1" FOREIGN KEY ("ADMINID")REFERENCES "ADMIN" ("ADMINID") ON DELETE CASCADE;

ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_ADMIN_TO_NOTICE_1" FOREIGN KEY ("ADMINID")REFERENCES "ADMIN" ("ADMINID") ON DELETE CASCADE;

ALTER TABLE "PMANAGE" ADD CONSTRAINT "FK_ADMIN_TO_PMANAGE_1" FOREIGN KEY ("ADMINID")REFERENCES "ADMIN" ("ADMINID") ON DELETE CASCADE;

ALTER TABLE "PMANAGE" ADD CONSTRAINT "FK_PRODUCT_TO_PMANAGE_1" FOREIGN KEY ("PCODE")REFERENCES "PRODUCT" ("PCODE") ON DELETE CASCADE;

ALTER TABLE "UMANAGE" ADD CONSTRAINT "FK_USER_TO_UMANAGE_1" FOREIGN KEY ("USERID")REFERENCES "MEMBER" ("USERID") ON DELETE CASCADE;

ALTER TABLE "UMANAGE" ADD CONSTRAINT "FK_ADMIN_TO_UMANAGE_1" FOREIGN KEY ("ADMINID")REFERENCES "ADMIN" ("ADMINID") ON DELETE CASCADE;

ALTER TABLE "ORDER" ADD CONSTRAINT "FK_PRODUCT_TO_ORDER_1" FOREIGN KEY ("PCODE")REFERENCES "PRODUCT" ("PCODE") ON DELETE CASCADE;

ALTER TABLE "FILE" ADD CONSTRAINT "FK_PRODUCT_TO_FILE_1" FOREIGN KEY ("PCODE")REFERENCES "PRODUCT" ("PCODE") ON DELETE CASCADE;

ALTER TABLE "INQUIRYCOMMENT" ADD CONSTRAINT "FK_ADMIN_TO_INQUIRYCOMMENT_1" FOREIGN KEY ("ADMINID")REFERENCES "ADMIN" ("ADMINID") ON DELETE CASCADE;